/*
 * Secret Message Exchange Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2001 struct {

	Id string `json:"id,omitempty"`

	Link string `json:"link,omitempty"`
}
