/*
 * Secret Message Exchange Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {

	UserId string `json:"user_id,omitempty"`

	Token string `json:"token,omitempty"`
}
